In [1]:
import pandas as pd

In [2]:
meta_data = pd.read_excel('List_Of_Restaurants.xlsx')
meta_data.head(5)

,Restaurant_name,Rating_out_of_5,rating_name,Review_number,Cuisine_Type,Location,Image_URL,Price_range,Website,Cuisines_list,Contact_Number,Opening_Hours,About Section,5_Reviews
0,Eastway Brasserie,3.7,Very Good,1461,British,Liverpool Street,https://images.otstatic.com/prod/24868488/1/me...,£25 and under,https://eastwaybrasserie.com/?src=prop_misc_lo...,"British, Contemporary British, Dining Bar\n",020 7618 7400\n,"Breakfast\nDaily 07:00–11:30\nLunch\nMon–Fri, ...","Boasting an AA Rosette, Eastway is an all-day ...","Beautiful place, good service, nice food. Drin..."
1,Gaucho City,4.3,Awesome,1730,Steak,Fenchurch Street,https://images.otstatic.com/prod/25200368/1/me...,£41 and over,http://www.gauchorestaurants.co.uk/,"Steak, Argentinian, Latin American",020 7626 5180,Mon–Fri 12:00–22:00\nSat 17:00–22:00,\nGaucho City is one of London’s hidden gems. ...,"The decor was horrendous, with dirty surfaces ..."
2,M Threadneedle Street,4.4,Awesome,2264,Steakhouse,Bank,https://images.otstatic.com/prod/27181612/1/me...,£41 and over,http://www.mrestaurants.co.uk/,"Steakhouse, Steak, Seafood",020 3327 7770,Mon–Sat 12:00–22:00,M Restaurants take inspiration from six differ...,Beautiful venue! But… Did the bottomless brunc...
3,Miyako at Andaz,4.0,Excellent,225,Japanese,Liverpool Street,https://images.otstatic.com/prod/27877738/4/me...,£26 to £40,https://www.hyattrestaurants.com/en/dining/uk/...,Japanese,020 7618 7100,Tue–Sat 17:00–22:00\nSit down & Takeaway\nTue–...,"Boasting an AA Rosette, Miyako is a serene han...",Amazing sushi in a very small traditional Japa...
4,Hawksmoor Guildhall,4.7,Exceptional,3285,Steakhouse,Bank,https://resizer.otstatic.com/v2/photos/medium/...,£25 and under,https://thehawksmoor.com/locations/guildhall/,"Steakhouse, Seafood, British",020 7397 8120,Mon–Fri 17:00–21:30\nTue–Fri 12:00–14:30\nSat ...,"Situated in the heart of The City, Hawksmoor G...","The Hawksmoor never fails, great food,good ser..."

In [4]:
C = meta_data['Rating_out_of_5'].mean()
C

4.383333333333335

In [7]:
m = meta_data['Review_number'].quantile(0.9)
m

2259.3

In [13]:
q_restaurants = meta_data.copy().loc[meta_data['Review_number'] >= m]
q_restaurants.shape

(11, 14)

In [14]:
meta_data.shape

(102, 14)

In [12]:
def weighted_rating(x, m=m, C=C):
    v = x['Review_number']
    R = x['Rating_out_of_5']
    return (v/(v+m) * R) + (m/(m+v) * C)

In [36]:
q_restaurants['score'] = q_restaurants.apply(weighted_rating, axis=1)
q_restaurants.head(20)

,Restaurant_name,Rating_out_of_5,rating_name,Review_number,Cuisine_Type,Location,Image_URL,Price_range,Website,Cuisines_list,Contact_Number,Opening_Hours,About Section,5_Reviews,score
42,St. John,4.8,Exceptional,2986,British,Farringdon,https://images.otstatic.com/prod1/41871637/1/m...,£41 and over,\nhttp://www.stjohnrestaurant.com/,British,020 7251 0848,Lunch\nMon–Sat 12:00–15:00\nSun 12:00–16:00\nD...,Fergus Henderson’s original home of “Nose to T...,Half of the menu was out of stock despite it b...,4.620530
4,Hawksmoor Guildhall,4.7,Exceptional,3285,Steakhouse,Bank,https://resizer.otstatic.com/v2/photos/medium/...,£25 and under,https://thehawksmoor.com/locations/guildhall/,"Steakhouse, Seafood, British",020 7397 8120,Mon–Fri 17:00–21:30\nTue–Fri 12:00–14:30\nSat ...,"Situated in the heart of The City, Hawksmoor G...","The Hawksmoor never fails, great food,good ser...",4.570958
18,Coq d’Argent Restaurant,4.5,Awesome,5702,French,Bank,https://images.otstatic.com/prod/24611265/1/me...,£41 and over,\nhttp://www.coqdargent.co.uk/,French,020 7395 5000,\nLunch\nMon–Fri 12:00–15:00\nBrunch\nSat 12:0...,High above the City you'll find a classic Fren...,"This is the perfect venue for a business meal,...",4.466892
38,The Ivy City Garden,4.5,Awesome,4712,Contemporary British,Liverpool Street,https://images.otstatic.com/prod/25086287/1/me...,£25 and under,\nhttps://theivycitygarden.com/,"Contemporary British, British, Breakfast",020 3146 7744,Mon–Fri 08:00–00:00\nSat 11:00–00:00\nSun 11:0...,"Located in the historic Bishopsgate Gardens, T...","Always good here, food is consistently good an...",4.462190
71,Paternoster Chop House,4.5,Awesome,2336,British,St Paul's,https://images.otstatic.com/prod1/41938559/2/m...,£26 to £40,\nhttp://www.paternosterchophouse.co.uk/,"British, Steakhouse",020 7029 9400,Tue 12:00–21:00\nSat 12:00–22:30\nSun 12:00–16:30,We are bringing back the great British Chop Ho...,Very harsh environment. There was a particular...,4.442640
67,Kenza,4.4,Awesome,3584,Lebanese,Aldgate,https://images.otstatic.com/prod/23679952/1/me...,£26 to £40,\nhttp://www.kenza-restaurant.com/,"Lebanese, Middle Eastern, Moroccan",020 7929 5533,Hours of Operation\nLunch\nMon–Fri 12:00–17:00...,"Oozing with rich fabrics, cushions, carved tab...","Lovely restaurant, amazing food, great atmosph...",4.393556
2,M Threadneedle Street,4.4,Awesome,2264,Steakhouse,Bank,https://images.otstatic.com/prod/27181612/1/me...,£41 and over,http://www.mrestaurants.co.uk/,"Steakhouse, Steak, Seafood",020 3327 7770,Mon–Sat 12:00–22:00,M Restaurants take inspiration from six differ...,Beautiful venue! But… Did the bottomless brunc...,4.391675
41,Yauatcha City,4.3,Awesome,2351,Chinese,Liverpool Street,https://images.otstatic.com/prod/23889651/1/me...,£25 and under,\nhttp://www.yauatcha.com/,Chinese,020 3817 9888,"Tue, Wed 11:30–22:00\nThu, Fri 11:30–23:00\nSa...",Yauatcha City opened in May 2015 in Broadgate ...,"Service was terrible, struggled to get waiters...",4.340838
17,1 Lombard Street Brasserie,4.3,Awesome,3766,British,Bank,https://images.otstatic.com/prod1/42304143/3/m...,£41 and over,\nhttp://www.1lombardstreet.com/,"British, Comfort Food, Modern European",020 7929 6611,Breakfast\nMon–Fri 07:30–09:45\nLunch\nMon–Fri...,1 Lombard Street is one of the longest standin...,Great venue to have a cordial business breakfa...,4.331247
30,Cinnamon Kitchen,4.2,Awesome,2636,Indian,Liverpool Street,https://images.otstatic.com/prod1/47090119/3/m...,£26 to £40,\nhttp://www.cinnamon-kitchen.com/,Casual Dining,020 7626 5000,Tue–Sat 12:00–23:00\nSun 12:00–22:00,Located in the striking Devonshire Square deve...,"First time I'd been and brought clients, they ...",4.284613
16,Bread Street Kitchen & Bar — St Paul's,4.2,Awesome,4164,Modern European,St Paul's,https://images.otstatic.com/prod/26336524/3/me...,£26 to £40,\nhttps://www.gordonramsayrestaurants.com/brea...,"Modern European, British, Cocktail Bar",020 3030 4050,"Mon–Wed 07:30–00:00\nThu, Fri 07:30–01:00\nSat...",Bread Street Kitchen in St Paul's is a bustlin...,Really disappointed with the lack of vegan opt...,4.264485

In [16]:
q_restaurants = q_restaurants.sort_values('score', ascending=False)
q_restaurants[['Restaurant_name', 'Rating_out_of_5', 'Review_number', 'score']].head(20)

,Restaurant_name,Rating_out_of_5,Review_number,score
42,St. John,4.8,2986,4.620530
4,Hawksmoor Guildhall,4.7,3285,4.570958
18,Coq d’Argent Restaurant,4.5,5702,4.466892
38,The Ivy City Garden,4.5,4712,4.462190
71,Paternoster Chop House,4.5,2336,4.442640
67,Kenza,4.4,3584,4.393556
2,M Threadneedle Street,4.4,2264,4.391675
41,Yauatcha City,4.3,2351,4.340838
17,1 Lombard Street Brasserie,4.3,3766,4.331247
30,Cinnamon Kitchen,4.2,2636,4.284613
16,Bread Street Kitchen & Bar — St Paul's,4.2,4164,4.264485

In [17]:
meta_data['About Section'].head()

0    Boasting an AA Rosette, Eastway is an all-day ...
1    \nGaucho City is one of London’s hidden gems. ...
2    M Restaurants take inspiration from six differ...
3    Boasting an AA Rosette, Miyako is a serene han...
4    Situated in the heart of The City, Hawksmoor G...
Name: About Section, dtype: object

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [25]:
tfidf = TfidfVectorizer(stop_words='english')
meta_data['About Section'] = meta_data['About Section'].fillna('')
tfidf_matrix = tfidf.fit_transform(meta_data['About Section'])
tfidf_matrix.shape

(102, 2128)

In [26]:
tfidf.get_feature_names()[1000:1010]

['huts',
 'hwa',
 'hymn',
 'iberica',
 'ibericarestaurants',
 'ibérica',
 'idea',
 'ideal',
 'ideally',
 'ii']

In [23]:
from sklearn.metrics.pairwise import linear_kernel

In [28]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim.shape

(102, 102)

In [29]:
cosine_sim[1]

array([0.03502032, 1.        , 0.06618543, 0.03332834, 0.16553853,
       0.03867051, 0.02646854, 0.07698137, 0.10020757, 0.02398163,
       0.08721966, 0.04610012, 0.05604037, 0.05700762, 0.02768416,
       0.07238715, 0.03656732, 0.09315105, 0.02705909, 0.10858698,
       0.04103333, 0.01780643, 0.00676204, 0.08633974, 0.04514338,
       0.06841702, 0.06337484, 0.03251728, 0.02007578, 0.17132875,
       0.03795565, 0.00719673, 0.02389335, 0.0212326 , 0.03344808,
       0.06490088, 0.0443706 , 0.01679995, 0.08101555, 0.04976478,
       0.05427646, 0.01860124, 0.01177268, 0.08011055, 0.21793253,
       0.0264439 , 0.01293421, 0.00741033, 0.05339284, 0.06347272,
       0.00799782, 0.072114  , 0.08032297, 0.05354446, 0.01704401,
       0.03258325, 0.1150464 , 0.06029971, 0.02125866, 0.14407451,
       0.05512908, 0.01867254, 0.        , 0.06753106, 0.04538693,
       0.05812219, 0.02071976, 0.03496568, 0.07607711, 0.05305663,
       0.04553104, 0.00301496, 0.04225253, 0.0596115 , 0.0395322 ,
       0.01412178, 0.003275  , 0.06007879, 0.05389678, 0.10075377,
       0.05523077, 0.03609268, 0.07966562, 0.05521231, 0.05415803,
       0.01631329, 0.02831159, 0.01102248, 0.03361412, 0.10837507,
       0.07220896, 0.03520706, 0.00614819, 0.00203071, 0.03045064,
       0.        , 0.03045064, 0.02059169, 0.01804104, 0.02681539,
       0.04664259, 0.11029318])

In [30]:
indices = pd.Series(meta_data.index, index=meta_data['Restaurant_name']).drop_duplicates()
indices[:10]

Restaurant_name
Eastway Brasserie                  0
Gaucho City                        1
M Threadneedle Street              2
Miyako at Andaz                    3
Hawksmoor Guildhall                4
Piazza Italiana                    5
Kaia at The Ned                    6
Cabotte                            7
Lutyens Grill at The Ned           8
Electric Bar & Diner at The Ned    9
dtype: int64

In [34]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]
    
    sim_scores = list(enumerate(cosine_sim[idx]))
    
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    sim_scores = sim_scores[1:11]
    
    restaurants_indices = [i[0] for i in sim_scores]
    
    return meta_data['Restaurant_name'].iloc[restaurants_indices]

In [35]:
get_recommendations('Kenza')

19                               MBER
10                       Caravan City
7                             Cabotte
53                  Hithe + Seek\nNEW
49             The Quality Chop House
57    Kirin Chinese Restaurant London
5                     Piazza Italiana
0                   Eastway Brasserie
82                      Mumbai Square
4                 Hawksmoor Guildhall
Name: Restaurant_name, dtype: object

In [37]:
meta_data['Cuisine_Type'].unique()

array(['British ', 'Steak', 'Steakhouse', 'Japanese', 'Italian',
       'Pan-Asian', 'French', 'American', 'Deli', 'Global, International',
       'Californian', 'Tapas / Small Plates', 'Spanish',
       'Modern European ', 'Asian', 'Indian', 'Pizzeria',
       'Contemporary British ', 'Vegan', 'Burgers', 'Wine Bar',
       'Contemporary Asian', 'Chinese', 'Portuguese', 'Mediterranean',
       'Chinese (Canton) ', 'Seafood', 'Bar / Lounge / Bottle Service ',
       'Lebanese', 'Thai', 'Gastro Pub', 'International', 'Pub',
       'European', 'English', 'Pizza Bar', 'Korean'], dtype=object)